### ISSUE TITLE
Suggest: Use timelocal_modern/timegm_modern in SYNOPSIS

### ISSUE THREAD

**Issue by skaji** [houseabsolute/Time-Local#10]
If you **strongly** encourage us to use timelocal_modern/timegm_modern instead of timelocal/timegm,
then why don't you use timelocal_modern/timegm_modern in SYNOPSIS too?

**Comment by autarch** [comment]
Good point. A PR would be welcome.

**Comment by skaji** [comment]
Nice!

... I noticed that just changing SYNOPSIS may conflict with the following sentence:
> This module provides functions that are the inverse of built-in perl functions localtime() and gmtime().

**Comment by skaji** [comment]
```perl
use Time::Local qw(timelocal timegm timelocal_modern timegm_modern);

my $time = time;

# These are true
$time == timelocal localtime $time;
$time == timegm gmtime $time;

# These are false
$time == timelocal_modern localtime $time;
$time == timegm_modern gmtime $time;
```

**Comment by autarch** [comment]
Yeah, I wonder if it's better to rethink these subs (or provide yet another version that is truly reversable). Bleah, it's a bit of a mess.

**Comment by skaji** [comment]
I prefer that Time-Local provides functions that are truly reversible.
On the other hand, I also agree with you that it is a mess :/

**Comment by autarch** [comment]
The new `*_posix` functions are now the ones shown in the SYNOPSIS.
