### ISSUE TITLE
Test fail while building perl-5.28.1

### ISSUE THREAD

**Issue by KES777** [houseabsolute/Time-Local#17]
```
t/../cpan/Time-Local/t/Local ... #   Failed test 'timelocal year for 1970 1 2 0 0 0'
#   at t/Local.t line 109.
#          got: '170'
#     expected: '70'
#   Failed test 'timegm year for 1970 1 2 0 0 0'
#   at t/Local.t line 124.
#          got: '170'
#     expected: '70'
# Looks like you failed 2 tests of 187.
FAILED at test 6
Failed 1 test out of 0, 0.00% okay.
	../cpan/Time-Local/t/Local.t
```

[build.perl-5.28.1.log](https://github.com/houseabsolute/Time-Local/files/5719441/build.perl-5.28.1.log)

**Comment by autarch** [comment]
Older versions of Perl ship older versions of Time::Local. I'm 99% sure that this is the test bug that was fixed in the 1.27 release. There's nothing that can be done about the fact that older versions of this module have started failing their tests.
